### ISSUE TITLE
When column type is not T, constructed column has internal array with wrong type

### ISSUE THREAD

**Issue by kchanqvq** [sirherrbatka/vellum-csv#1]
First, thanks for your work at bringing data frame to Common Lisp!

To reproduce, have a test.csv:
```
1
```

then
```
(let ((test-table (vellum:copy-from :csv "test.csv" :columns 
                                           '((:name a :type fixnum))
                                           :includes-header-p nil)))
         (cl-ds.alg:to-vector (vellum.table:column-at test-table 'a)))
```

This gives error
```
The value
  #(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0)

is not of type
  (OR SIMPLE-VECTOR NULL)
```

After digging for a bit, it seems that the constructed column has a `%tail` array with `array-element-type=fixnum`, while the rest of the system (in this case the `cl-ds:across` method) assume it to be a `simple-vector`, i.e. `array-element-type=t`. I tried to fix it but couldn't pin down where goes wrong...

**Comment by sirherrbatka** [comment]
Hello, yes you are 100% correct. Problem was corrected in the freshest commit in the main vellum repo, you can check it there.

**Comment by kchanqvq** [comment]
I see a number of other `simple-vector` declaration in `src/column/implementation.lisp`. Are they problematic as well?

**Comment by sirherrbatka** [comment]
Possibly, I will inspect this next week.

**Comment by kchanqvq** [comment]
Thanks!
